---
- hosts: 172.31.49.20
  become: True
  tasks:
   - name: Install Apache Server
     yum:
        name: httpd
        state: present
   - name: Enable  Apache on Reboot
     service:
        name: httpd
        enabled: True
   - name: Install Git
     yum:
        name: git
        state: present
   - name: Deploy Website from git
     git:
       repo: https://github.com/Aakash-Elango/demo-html
       dest: /var/www/html/
   - name: restart apache
     service:
        name: httpd
        state: restarted
...
